#!/bin/bash -e

# source debconf library
. /usr/share/debconf/confmodule

if [ "$1" = "remove" ] || [ "$1" = "purge" ]
then
  ## remove lines
  TMP="$(mktemp)"
  chmod 0600 "$TMP"

  # sed does not deletes the lines on direct editing ?:(
  sed '/<\!-- IServ Print BEGIN -->/,/<\!-- IServ Print END -->/d' /etc/iserv/security/pam_mount.conf.xml > "$TMP"
  if [ -L "/etc/security/pam_mount.conf.xml" ]
  then
    cp "$TMP" "/etc/iserv/security/pam_mount.conf.xml"
  else
    cp "$TMP" "/etc/security/pam_mount.conf.xml"
  fi
  rm -f "$TMP"
fi

if [ "$1" = "purge" ]
then
  db_purge
fi

